### ISSUE TITLE
Add Gas Token support to Trusted Migrate

### ISSUE THREAD

**Issue by dougstorm** [iearn-finance/zaps#25]
Add option to use gasToken on TrustedMigrate to improve gas cost for users migrating.

Contract: [TrustedVaultMigrator.sol](https://github.com/iearn-finance/zaps/blob/master/contracts/TrustedVaultMigrator.sol)
Spec:
Should be added as a mix in contract that other contracts in this repo can extend.
Should be a modifier that we can use on a specific method that we want to add support to it (see examples)

Nice to Have:
Tests (may be hard emulating with ganache fork)

References:

https://github.com/iearn-finance/yearn-vaults/pull/172/files
https://github.com/PSI-Passive-Income/DPEX-contracts/blob/028318900fe110abdd176f32f0c1ab2f8edbb3a9/contracts/abstracts/SafeGas.sol
https://github.com/stakewithus/uvault/blob/88330cf353cf5575aae81519cb88bf5976cf7fe8/contracts/GasRelayer.sol#L31

**Comment by fameal** [comment]
Progress here: #26

**Comment by dougstorm** [comment]
closed by #26
